ManifestType: installer
NestedInstallerFiles:
- RelativeFilePath: AILZ80ASM.exe
InstallerType: zip
ManifestVersion: 1.9.0
NestedInstallerType: portable
PackageVersion: 1.0.27
Installers:
- InstallerSha256: 9E1B761DF4ED8D8DDB4777946D260F8CB117C3184BDB6F513867D9D3C6E85AEF
  InstallerUrl: https://github.com/AILight/AILZ80ASM/releases/download/v1.0.27/AILZ80ASM.win-x64.v1.0.27.zip
  Architecture: x64
PackageIdentifier: AILight.AILZ80ASM
ReleaseDate: 2025-01-07

