PackageIdentifier: Morpheus.Bazarr
ManifestType: installer
InstallerLocale: en-US
InstallModes:
- silent
- silentWithProgress
AppsAndFeaturesEntries:
- ProductCode: '{EEC3B85A-0666-4A5A-BD10-9BD1C237FEF0}_is1'
  Publisher: Bazarr
InstallerType: zip
ReleaseDate: 2022-03-23
PackageVersion: "1.15"
NestedInstallerFiles:
- RelativeFilePath: Bazarr.exe
InstallationMetadata:
  DefaultInstallLocation: '%SystemDrive%\Bazarr'
NestedInstallerType: inno
ManifestVersion: 1.9.0
ElevationRequirement: elevatesSelf
Installers:
- Architecture: x86
  InstallerSha256: 69DFD1591BB0B6F479FFBADF1EB563692DED7C909997425097602DDA63F496EC
  InstallerUrl: https://github.com/bazarr/bazarr.github.io/releases/download/v1.15/Bazarr.zip
ProductCode: '{EEC3B85A-0666-4A5A-BD10-9BD1C237FEF0}_is1'

