ReleaseDate: 2025-01-16
FileExtensions:
- minisig
PackageIdentifier: jedisct1.minisign
InstallerType: zip
ManifestType: installer
ManifestVersion: 1.9.0
NestedInstallerFiles:
- PortableCommandAlias: minisign
  RelativeFilePath: minisign-win64/x86_64/minisign.exe
UpgradeBehavior: install
Commands:
- minisign
NestedInstallerType: portable
PackageVersion: "0.12"
Installers:
- InstallerSha256: 37B600344E20C19314B2E82813DB2BFDCC408B77B876F7727889DBD46D539479
  InstallerUrl: https://github.com/jedisct1/minisign/releases/download/0.12/minisign-0.12-win64.zip
  Architecture: x64

