InstallerType: nullsoft
PackageVersion: 15.3.0
PackageIdentifier: fairdataihub.SODA-for-SPARC
AppsAndFeaturesEntries:
- ProductCode: 4f40db07-30e8-5289-bfc9-fe077f74e495
ReleaseDate: 2024-12-30
ProductCode: 4f40db07-30e8-5289-bfc9-fe077f74e495
ManifestVersion: 1.9.0
ManifestType: installer
InstallerLocale: en-US
Installers:
- InstallerSha256: 9C919ED1E6895CE6BF4CCC950AE690F756EF35A9BFD63E3CF8B2E8A861B21408
  Architecture: x64
  InstallerUrl: https://github.com/fairdataihub/SODA-for-SPARC/releases/download/v15.3.0/soda-for-sparc-15.3.0-setup.exe

