InstallerType: nullsoft
ReleaseDate: 2024-12-10
ManifestVersion: 1.9.0
ProductCode: f1339da8-b3f2-5116-b780-aafa611bc7f7
InstallerLocale: en-US
PackageIdentifier: OxenLabs.Session
AppsAndFeaturesEntries:
- ProductCode: f1339da8-b3f2-5116-b780-aafa611bc7f7
  DisplayName: Session 1.14.3
ManifestType: installer
PackageVersion: 1.14.3
Installers:
- Architecture: x64
  InstallerSha256: 596E3776E80D5E87FE7A8BA150718D2469160FC51E095FA72E12F4257E95E46A
  InstallerUrl: https://github.com/oxen-io/session-desktop/releases/download/v1.14.3/session-desktop-win-x64-1.14.3.exe

