# Created with komac v2.11.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: FirebirdProject.Firebird.3
PackageVersion: 5.0.2
InstallerLocale: en-US
InstallerType: inno
ProductCode: FBDBServer_5_0_x64_is1
ReleaseDate: 2025-02-12
AppsAndFeaturesEntries:
- DisplayVersion: 5.0.2.1613
  ProductCode: FBDBServer_5_0_x64_is1
ElevationRequirement: elevatesSelf
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/FirebirdSQL/firebird/releases/download/v5.0.2/Firebird-5.0.2.1613-0-windows-x64-withDebugSymbols.exe
  InstallerSha256: C8F7BAE0407681CA0580D7251841F118FBDE16ADFADCB02D980B94896BF6B5C1
ManifestType: installer
ManifestVersion: 1.9.0
