ManifestVersion: 1.9.0
InstallModes:
- silent
- silentWithProgress
UpgradeBehavior: uninstallPrevious
Installers:
- Architecture: x64
  InstallerSha256: A830E9E6DEE64819CFAEF2D8B05D87F267517C6C2B6F5FBD367624D5F1158C96
  InstallerUrl: https://github.com/aloneguid/parquet-dotnet/releases/download/5.1.1/floor-win-x64-5.1.1.zip
PackageIdentifier: aloneguid.ParquetDotnet.floor
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: floor.exe
InstallerType: zip
ReleaseDate: 2025-02-27
PackageVersion: 5.1.1
ManifestType: installer

