PackageIdentifier: MongoDB.Compass.Community
ManifestType: installer
InstallerLocale: en-US
AppsAndFeaturesEntries:
- DisplayName: MongoDB Compass
  UpgradeCode: '{0152273D-2F9F-4913-B67F-0FCD3557FFD1}'
  Publisher: MongoDB Inc
  ProductCode: '{191C7FFA-FCEE-4B85-ADCC-DF93D267195A}'
InstallerType: wix
ReleaseDate: 2025-02-13
Scope: machine
PackageVersion: 1.45.3
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%\MongoDB Compass'
ManifestVersion: 1.9.0
Installers:
- Architecture: x64
  InstallerSha256: C1752215171B797438B249BF33E559AD141C56A595FFD0A09C7B3A0D6E59CC6E
  InstallerUrl: https://github.com/mongodb-js/compass/releases/download/v1.45.3/mongodb-compass-1.45.3-win32-x64.msi
ProductCode: '{191C7FFA-FCEE-4B85-ADCC-DF93D267195A}'

