Installers:
- Architecture: x86
  InstallerSha256: 58220F5307DB225419520C0D2BBFB64128961D0F4F201E4C03DC5B06171F9916
  InstallerUrl: https://github.com/maplemedia/pulse-sms-desktop/releases/download/v4.5.3/pulse-sms-4.5.3.exe
ManifestVersion: 1.9.0
PackageIdentifier: MapleMedia.PulseSMS
PackageVersion: 4.5.3
InstallerType: nullsoft
InstallerLocale: en-US
UpgradeBehavior: install
AppsAndFeaturesEntries:
- ProductCode: b48fe4d9-ee4c-5cce-b155-58a841ce5555
  DisplayName: Pulse SMS 4.5.3
ProductCode: b48fe4d9-ee4c-5cce-b155-58a841ce5555
ManifestType: installer
ReleaseDate: 2023-01-10

