ReleaseDate: 2025-02-02
NestedInstallerType: portable
PackageIdentifier: hfiref0x.WinObjEx64
PackageVersion: 2.0.6
ManifestVersion: 1.9.0
Installers:
- InstallerSha256: E3F8FD5004627BD2A92BFD96674CC55CB181E295DE48B84BAE4575E3C9FF1293
  Architecture: neutral
  InstallerUrl: https://github.com/hfiref0x/WinObjEx64/releases/download/v2.0.6/WinObjEx64_2.0.6.zip
NestedInstallerFiles:
- RelativeFilePath: WinObjEx64.exe
ManifestType: installer
InstallerType: zip

