ReleaseDate: 2023-03-11
ManifestType: installer
PackageIdentifier: KatKoyn.KatKoynCore
PackageVersion: 2.4.0
Installers:
- InstallerSha256: FD9039AC1D54F2286643B8F627BE5682B72FA816568C6B439A43FC4B04EE5E97
  InstallerUrl: https://github.com/KatKoyn/katkoyn-client/releases/download/v2.4.0/KatKoyn-Wallet-x86_64-win.zip
  Architecture: x64
InstallerType: zip
ManifestVersion: 1.9.0
NestedInstallerFiles:
- PortableCommandAlias: bench_katkoyn
  RelativeFilePath: depends\x86_64-w64-mingw32\bin\bench_katkoyn.exe
- PortableCommandAlias: katkoyn
  RelativeFilePath: depends\x86_64-w64-mingw32\bin\katkoyn-cli.exe
- PortableCommandAlias: katkoyn-qt
  RelativeFilePath: depends\x86_64-w64-mingw32\bin\katkoyn-qt.exe
- PortableCommandAlias: katkoyn-tx
  RelativeFilePath: depends\x86_64-w64-mingw32\bin\katkoyn-tx.exe
- PortableCommandAlias: katkoynd
  RelativeFilePath: depends\x86_64-w64-mingw32\bin\katkoynd.exe
NestedInstallerType: portable

