InstallerType: zip
PackageVersion: 2025.2.10.0
PackageIdentifier: facebook.watchman
ArchiveBinariesDependOnPath: true
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.VCRedist.2015+.x64
ReleaseDate: 2025-02-10
ManifestVersion: 1.9.0
NestedInstallerFiles:
- RelativeFilePath: watchman-v2025.02.10.00-windows/bin/watchman-diag.exe
  PortableCommandAlias: watchman-diag
- RelativeFilePath: watchman-v2025.02.10.00-windows/bin/watchman-make.exe
  PortableCommandAlias: watchman-make
- RelativeFilePath: watchman-v2025.02.10.00-windows/bin/watchman-replicate-subscription.exe
  PortableCommandAlias: watchman-replicate-subscription
- RelativeFilePath: watchman-v2025.02.10.00-windows/bin/watchman-wait.exe
  PortableCommandAlias: watchman-wait
- RelativeFilePath: watchman-v2025.02.10.00-windows/bin/watchman.exe
  PortableCommandAlias: watchman
- RelativeFilePath: watchman-v2025.02.10.00-windows/bin/watchmanctl.exe
  PortableCommandAlias: watchmanctl
ManifestType: installer
NestedInstallerType: portable
Installers:
- InstallerSha256: 37B7BD9C4E50CC4DF12288E66FC4735F72072755273DD592B45725DFA082E3EF
  Architecture: x64
  InstallerUrl: https://github.com/facebook/watchman/releases/download/v2025.02.10.00/watchman-v2025.02.10.00-windows.zip

