ReleaseDate: 2025-01-04
NestedInstallerType: portable
PackageIdentifier: houmain.spright
PackageVersion: 3.5.4
ManifestVersion: 1.9.0
Installers:
- InstallerSha256: 627A1A2B602B2F013FF46BAB1579494422CFCE0546D37DA707869B7AECDDB47B
  Architecture: x64
  InstallerUrl: https://github.com/houmain/spright/releases/download/3.5.4/spright-3.5.4-win64.zip
ManifestType: installer
NestedInstallerFiles:
- RelativeFilePath: spright-3.5.4-win64/spright.exe
Commands:
- spright
InstallerType: zip

