PackageIdentifier: MichalDuda.VookiImageViewer
ManifestType: installer
InstallerLocale: en-US
AppsAndFeaturesEntries:
- ProductCode: '{00E53F66-5799-4C9B-A7A1-5CF016E9ED4B}'
  UpgradeCode: '{91FA8A80-C971-408A-A735-4EB3D230D9F6}'
  DisplayVersion: 25.02.15
InstallerType: wix
ReleaseDate: 2025-02-15
Scope: machine
PackageVersion: 2025.2.15
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%\.\VookiImageViewer'
ManifestVersion: 1.9.0
Installers:
- Architecture: x64
  InstallerSha256: 02967A93398AD5EEA760F26573E97685DAF7269B77BCCEF832F277D144CF0A3F
  InstallerUrl: https://github.com/vookimedlo/vooki-image-viewer/releases/download/v2025.02.15/VookiImageViewer-2025.02.15-win64-x64.msi
ProductCode: '{00E53F66-5799-4C9B-A7A1-5CF016E9ED4B}'

