InstallModes:
- silent
- silentWithProgress
ManifestType: installer
NestedInstallerFiles:
- RelativeFilePath: floor.exe
InstallerType: zip
ManifestVersion: 1.9.0
NestedInstallerType: portable
PackageVersion: 5.1.0
Installers:
- InstallerSha256: B90B2B1218C79F0815907CD60458A35997405FC211932BBFC616EF5C633824FE
  InstallerUrl: https://github.com/aloneguid/parquet-dotnet/releases/download/5.1.0/floor-win-x64-5.1.0.zip
  Architecture: x64
UpgradeBehavior: uninstallPrevious
PackageIdentifier: aloneguid.ParquetDotnet.floor
ReleaseDate: 2025-01-30

