PackageVersion: 3.2.0
FileExtensions:
- .ecrc
- .editorconfig
- .editorconfig-checker.json
ReleaseDate: 2025-01-27
UpgradeBehavior: install
NestedInstallerType: portable
Commands:
- editorconfig-checker
PackageIdentifier: EditorConfig-Checker.EditorConfig-Checker
ManifestVersion: 1.9.0
InstallerType: zip
ManifestType: installer
Installers:
- InstallerSha256: 512235C23F19099B2FCCC9F0B45484F608F380899DB998A39BDAC48804327CBE
  NestedInstallerFiles:
  - RelativeFilePath: bin/ec-windows-386.exe
  Architecture: x86
  InstallerUrl: https://github.com/editorconfig-checker/editorconfig-checker/releases/download/v3.2.0/ec-windows-386.zip
- InstallerSha256: AF614995342FDF51308895F0DF04C40D88D22B345C8DF1DC7B5B379C1C54D441
  NestedInstallerFiles:
  - RelativeFilePath: bin/ec-windows-amd64.exe
  Architecture: x64
  InstallerUrl: https://github.com/editorconfig-checker/editorconfig-checker/releases/download/v3.2.0/ec-windows-amd64.zip
- InstallerSha256: 5A0D692E430788AEDEB613A132F4AC23309015E4962A0745DF728990F12A690E
  NestedInstallerFiles:
  - RelativeFilePath: bin/ec-windows-armv6.exe
  Architecture: arm
  InstallerUrl: https://github.com/editorconfig-checker/editorconfig-checker/releases/download/v3.2.0/ec-windows-armv6.zip
- InstallerSha256: A212CE886B95C7EDE06888B6C2356A1AF77BA1C721FA20C55015D3051342AA63
  NestedInstallerFiles:
  - RelativeFilePath: bin/ec-windows-arm64.exe
  Architecture: arm64
  InstallerUrl: https://github.com/editorconfig-checker/editorconfig-checker/releases/download/v3.2.0/ec-windows-arm64.zip

