ReleaseDate: 2025-01-14
NestedInstallerType: portable
PackageIdentifier: HiroshibaKazuyuki.VOICEVOX
PackageVersion: 0.22.4
ManifestVersion: 1.9.0
Installers:
- InstallerSha256: D3245955DFB76A2848626DE11D66D66D6795D39C56026974E64188311E13692C
  Architecture: neutral
  InstallerUrl: https://github.com/VOICEVOX/voicevox/releases/download/0.22.4/voicevox-windows-cpu-0.22.4.zip
NestedInstallerFiles:
- RelativeFilePath: VOICEVOX\VOICEVOX.exe
ManifestType: installer
InstallerType: zip

