ReleaseDate: 2023-09-09
AppsAndFeaturesEntries:
- DisplayVersion: 0.2.0+3
  ProductCode: FBCAB0B1-8171-40FA-B28E-234B17743354_is1
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.VCRedist.2015+.x64
PackageIdentifier: KRTirtho.Flemozi
InstallerType: inno
InstallerLocale: en-US
ManifestVersion: 1.9.0
Platform:
- Windows.Desktop
InstallationMetadata:
  DefaultInstallLocation: Flemozi
ManifestType: installer
ProductCode: FBCAB0B1-8171-40FA-B28E-234B17743354_is1
PackageVersion: 0.2.0
Installers:
- InstallerSwitches:
    Custom: /CURRENTUSER
  InstallerSha256: 2A1DB28077D01E014E7573C6AE37D6CAD482DB4823C13C35FED2A5406B90011F
  InstallerUrl: https://github.com/KRTirtho/flemozi/releases/download/v0.2.0/Flemozi-windows-x86_64-setup.exe
  Scope: user
  Architecture: x64
- InstallerSwitches:
    Custom: /ALLUSERS
  InstallerSha256: 2A1DB28077D01E014E7573C6AE37D6CAD482DB4823C13C35FED2A5406B90011F
  InstallerUrl: https://github.com/KRTirtho/flemozi/releases/download/v0.2.0/Flemozi-windows-x86_64-setup.exe
  Scope: machine
  Architecture: x64

