ReleaseDate: 2025-02-14
ManifestType: installer
PackageIdentifier: kcl-lang.kcl
PackageVersion: 0.11.1
Installers:
- InstallerSha256: 6154D6C2131A5C0C7A1C3C6A050DFEB91ABA6F10E7E00BFF3BC95AA155C2959D
  InstallerUrl: https://github.com/kcl-lang/cli/releases/download/v0.11.1/kcl-v0.11.1-windows-amd64.zip
  Architecture: x64
- InstallerSha256: CBA61C414942C04488EFC925693A889998B83C5939F873067747397EBC680765
  InstallerUrl: https://github.com/kcl-lang/cli/releases/download/v0.11.1/kcl-v0.11.1-windows-arm64.zip
  Architecture: arm64
UpgradeBehavior: install
InstallerType: zip
ManifestVersion: 1.9.0
NestedInstallerFiles:
- RelativeFilePath: kcl.exe
NestedInstallerType: portable

