# Created with komac v2.11.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: DuckStudio.FufuDevTools
PackageVersion: 2025.2.14.1314
InstallerLocale: en-US
InstallerType: inno
Scope: machine
UpgradeBehavior: install
Commands:
- ffdev
Protocols:
- https
ProductCode: 芙芙工具箱开发工具包_is1
ReleaseDate: 2025-02-13
AppsAndFeaturesEntries:
- Publisher: DuckStudio
  ProductCode: 芙芙工具箱开发工具包_is1
ElevationRequirement: elevatesSelf
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%\Fufu_Dev_Tools'
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/DuckDuckStudio/Fufu_Dev_Tools/releases/download/2025.02.14.1314/Fufu_Dev_Tools_Setup_2025.02.14.1314.exe
  InstallerSha256: 883AD4B929720178EF137D4CE1D89DFBABD5368024E886CED4B178DC9A6E4426
ManifestType: installer
ManifestVersion: 1.9.0
