ReleaseDate: 2025-02-15
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.DotNet.DesktopRuntime.7
ManifestType: installer
PackageIdentifier: KoalaBear84.OpenDirectoryDownloader
PackageVersion: 3.4.0.2
Installers:
- InstallerSha256: CDE6E8C2B41B814CFD2070DD77AC0BD00EFC0FEC50A9A03CEC898063A38E6DA8
  InstallerUrl: https://github.com/KoalaBear84/OpenDirectoryDownloader/releases/download/v3.4.0.2/OpenDirectoryDownloader-3.4.0.2-win-x64.zip
  Architecture: x64
InstallerType: zip
ManifestVersion: 1.9.0
NestedInstallerFiles:
- RelativeFilePath: OpenDirectoryDownloader.exe
NestedInstallerType: portable

