InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles(x86)%\Memento'
ProductCode: Ripose Memento
InstallModes:
- interactive
- silent
InstallerType: nullsoft
InstallerLocale: en-US
Scope: machine
AppsAndFeaturesEntries:
- ProductCode: Ripose Memento
  DisplayName: Memento - An mpv-based video player for studying Japanese.
  DisplayVersion: 0.5.6-0
ManifestVersion: 1.9.0
Installers:
- Architecture: x64
  InstallerSha256: 1A8330E1341CED1E915B5E0543FEE1A4C70C0350E50777EEB5D1848FF81F1F0D
  InstallerUrl: https://github.com/ripose-jp/Memento/releases/download/v1.5.0/Memento_Windows_x86_64_Installer.exe
ManifestType: installer
UpgradeBehavior: install
ReleaseDate: 2025-01-06
PackageVersion: 1.5.0
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.VCRedist.2010.x64
FileExtensions:
- mkv
- mp4
PackageIdentifier: Ripose.Memento

