InstallerLocale: en-US
PackageIdentifier: Eugeny.Tabby
UpgradeBehavior: install
InstallerSwitches:
  Upgrade: --updated
AppsAndFeaturesEntries:
- DisplayName: Tabby 1.0.221
  ProductCode: 71445fac-d6ef-5436-9da7-5a323762d7f5
ManifestType: installer
InstallerType: nullsoft
ReleaseDate: 2025-01-22
Installers:
- InstallerSha256: 3CDF3F2BAA16BF1283F92ACF8A151AFC120549A821C35FDE16B3EB73680B0C89
  Scope: user
  Architecture: x64
  InstallerSwitches:
    Custom: /currentuser
  InstallerUrl: https://github.com/Eugeny/tabby/releases/download/v1.0.221/tabby-1.0.221-setup-x64.exe
- InstallerSha256: 3CDF3F2BAA16BF1283F92ACF8A151AFC120549A821C35FDE16B3EB73680B0C89
  Scope: machine
  ElevationRequirement: elevationRequired
  Architecture: x64
  InstallerSwitches:
    Custom: /allusers
  InstallerUrl: https://github.com/Eugeny/tabby/releases/download/v1.0.221/tabby-1.0.221-setup-x64.exe
- InstallerSha256: 61CA36089B9F613AE152433AB5B793E70ABE87CB87ECFD307075EF053C2FB9B3
  Scope: user
  Architecture: arm64
  InstallerSwitches:
    Custom: /currentuser
  InstallerUrl: https://github.com/Eugeny/tabby/releases/download/v1.0.221/tabby-1.0.221-setup-arm64.exe
- InstallerSha256: 61CA36089B9F613AE152433AB5B793E70ABE87CB87ECFD307075EF053C2FB9B3
  Scope: machine
  ElevationRequirement: elevationRequired
  Architecture: arm64
  InstallerSwitches:
    Custom: /allusers
  InstallerUrl: https://github.com/Eugeny/tabby/releases/download/v1.0.221/tabby-1.0.221-setup-arm64.exe
ProductCode: 71445fac-d6ef-5436-9da7-5a323762d7f5
PackageVersion: 1.0.221
ManifestVersion: 1.9.0

