InstallerType: nullsoft
InstallerLocale: en-US
PackageVersion: 3.1.0
Scope: machine
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%\obs-studio'
ReleaseDate: 2023-12-25
AppsAndFeaturesEntries:
- ProductCode: obs-rtspserver
ManifestVersion: 1.9.0
ManifestType: installer
ProductCode: obs-rtspserver
PackageIdentifier: iamscottxu.obs-rtspserver
Installers:
- InstallerSha256: 29D26DE1C064C59E156087A3E0D0C720C3E0912961E8E8B1D76FEBD1013746C2
  Architecture: x64
  InstallerUrl: https://github.com/iamscottxu/obs-rtspserver/releases/download/v3.1.0/obs-rtspserver-v3.1.0-windows-installer.exe

