InstallerLocale: en-US
ManifestVersion: 1.9.0
PackageVersion: 2.1.2
AppsAndFeaturesEntries:
- DisplayName: Equibop 2.1.2
  ProductCode: c3f6e296-41ac-5ef9-aa06-55665efd99ac
Installers:
- InstallerSha256: 910587A9FAD1BBCBFA09A87235DB87F3F6D81C05DB52F7F7BB65FA334E7D52F2
  Architecture: x64
  InstallerUrl: https://github.com/Equicord/Equibop/releases/download/v2.1.2/Equibop-win-x64.exe
- InstallerSha256: B8307B151D4FD745D67AFBFA6AE7F53F2DB40218E2724DA75226444A9DCF9F48
  Architecture: arm64
  InstallerUrl: https://github.com/Equicord/Equibop/releases/download/v2.1.2/Equibop-win-arm64.exe
ManifestType: installer
PackageIdentifier: Equicord.Equibop
ProductCode: c3f6e296-41ac-5ef9-aa06-55665efd99ac
UpgradeBehavior: install
InstallerType: nullsoft
ReleaseDate: 2025-02-08

