InstallerType: inno
InstallerLocale: en-US
PackageVersion: 4.8.31.230
Scope: machine
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%\Midnight Commander'
ReleaseDate: 2024-03-31
AppsAndFeaturesEntries:
- ProductCode: '{CBB4464D-7081-4F1D-9F6D-F5288A4A9B82}_is1'
  DisplayVersion: '4.8.31 (build: 20240331-230)'
ElevationRequirement: elevatesSelf
Platform:
- Windows.Desktop
ManifestVersion: 1.9.0
ManifestType: installer
ProductCode: '{CBB4464D-7081-4F1D-9F6D-F5288A4A9B82}_is1'
PackageIdentifier: GNU.MidnightCommander
Installers:
- InstallerSha256: F8FA084F228BCB87F162D19CDA985282BC0F2D1C042D254964D1C49A4BFC4DD0
  Architecture: x86
  InstallerUrl: https://github.com/adamyg/mcwin32/releases/download/4.8.31.230/mcwin32-build230-setup.exe

