InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: policy.exe
ReleaseDate: 2025-02-03
ManifestVersion: 1.9.0
PackageIdentifier: OpenPolicyContainers.Policy
ManifestType: installer
PackageVersion: 0.3.0
Installers:
- Architecture: x64
  InstallerSha256: 3BCA28CD49D516FF44EC0D25D65D46FEF0D46D2C014624A4F6277BF0A2074366
  InstallerUrl: https://github.com/opcr-io/policy/releases/download/v0.3.0/policy0.3.0_windows_x86_64.zip

