# Created with komac v2.11.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: Docker.DockerCompose
PackageVersion: 2.33.0
InstallerType: portable
Commands:
- docker-compose
ReleaseDate: 2025-02-12
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/docker/compose/releases/download/v2.33.0/docker-compose-windows-x86_64.exe
  InstallerSha256: 1324E382E1A79EFAEE4BE288AAE847F8A2862ACF270D5621C17DFF3A10D5EE83
- Architecture: arm64
  InstallerUrl: https://github.com/docker/compose/releases/download/v2.33.0/docker-compose-windows-aarch64.exe
  InstallerSha256: 6A03DB6ECD49EB5A6EDBEB33201BEEA41A88DC31560135C469587A2533CC9DF0
ManifestType: installer
ManifestVersion: 1.9.0
