Dependencies:
  PackageDependencies:
  - MinimumVersion: 2.2.0.1000
    PackageIdentifier: dokan-dev.Dokany
PackageVersion: 1.4.4.5
ManifestType: installer
PackageIdentifier: BaileyBrown.cppcryptfs
ReleaseDate: 2024-11-11
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/bailey27/cppcryptfs/releases/download/1.4.4.5/cppcryptfs32.exe
  InstallerSha256: 9456CAA33E53C42A68C286FF5A5C6050C98F195375E4E18EA00EBA04C308E7C9
- Architecture: x64
  InstallerUrl: https://github.com/bailey27/cppcryptfs/releases/download/1.4.4.5/cppcryptfs.exe
  InstallerSha256: 15510C6F87EEAFC4D04C1D709173055F8519D2A18CF97A9D017BBFC9AEBBA7E3
ManifestVersion: 1.9.0
InstallerType: portable

