InstallerType: msi
InstallerLocale: und
PackageVersion: 2.0.7722.30975
Scope: user
InstallationMetadata: {}
ReleaseDate: 2021-12-07
AppsAndFeaturesEntries:
- ProductCode: '{27BA937E-88CF-46BD-9BDA-2426BDE4BA49}'
  DisplayVersion: 2.0.7722
  UpgradeCode: '{7EA17151-76E7-4E29-8F6A-621C1B4144C2}'
ManifestVersion: 1.9.0
ManifestType: installer
ProductCode: '{27BA937E-88CF-46BD-9BDA-2426BDE4BA49}'
PackageIdentifier: Gawindx.WinNUT
Installers:
- InstallerSha256: AFE7BB9F696ACA17FC2C4BF16DCFD4A70221F8114D987ACF71D51D1C4F3EEF4C
  Architecture: x86
  InstallerUrl: https://github.com/gawindx/WinNUT-Client/releases/download/v2.0.7722.30975/WinNUT-Setup.msi

