ElevationRequirement: elevatesSelf
ManifestType: installer
AppsAndFeaturesEntries:
- ProductCode: '{8A0E36A6-DE56-46B8-BCC3-C16D1BC759CC}_is1'
ReleaseDate: 2024-11-11
PackageIdentifier: JohannesPohl.UniversalRadioHacker
Scope: machine
InstallerLocale: en-US
ManifestVersion: 1.9.0
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%\Universal Radio Hacker'
InstallerType: inno
ProductCode: '{8A0E36A6-DE56-46B8-BCC3-C16D1BC759CC}_is1'
PackageVersion: 2.9.8
Installers:
- InstallerSha256: 3240AE5292594306B289113DCE4D442E3858DA4166EF00CEC87D7E10F262A2E2
  InstallerUrl: https://github.com/jopohl/urh/releases/download/v2.9.8/Universal.Radio.Hacker-2.9.8-x86.exe
  Architecture: x86
- InstallerSha256: 51EC7FF676A2383E89C35FF1ECA719BA82B88FD05E0AB7939E78AD88A482A67A
  InstallerUrl: https://github.com/jopohl/urh/releases/download/v2.9.8/Universal.Radio.Hacker-2.9.8-x64.exe
  Architecture: x64

