PackageVersion: 7.4.2
InstallerType: wix
Installers:
- InstallerSha256: 4D187D085BA88D10BD576733005FC4DE075AC678C525F8399FCDBC70C6C7E2C5
  Architecture: x64
  InstallerUrl: https://github.com/GAM-team/GAM/releases/download/v7.04.02/gam-7.04.02-windows-x86_64.msi
Scope: machine
ProductCode: '{C6302934-46AF-40A6-BBB3-6A3CA35CC8FF}'
InstallerLocale: en-US
PackageIdentifier: GAM-Team.gam
ManifestVersion: 1.9.0
ReleaseDate: 2025-02-14
InstallationMetadata:
  DefaultInstallLocation: .\GAM7
ManifestType: installer
AppsAndFeaturesEntries:
- ProductCode: '{C6302934-46AF-40A6-BBB3-6A3CA35CC8FF}'
  DisplayName: GAM7
  UpgradeCode: '{D86B52B2-EFE9-4F9D-8BA3-9D84B9B2D319}'

