InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%\PDFShow'
ProductCode: '{84420C1F-C236-31C3-95DF-80EC13960E1F}'
InstallerType: wix
InstallerLocale: en-US
Scope: machine
AppsAndFeaturesEntries:
- ProductCode: '{84420C1F-C236-31C3-95DF-80EC13960E1F}'
  UpgradeCode: '{F9D6E956-6040-3C9B-9D91-B11B4F209151}'
ManifestVersion: 1.9.0
Installers:
- Architecture: x64
  InstallerSha256: 17C690A69B91B036ADBF0F7D0DA2591E02067475A9BB6E83C33D06B3FE513466
  InstallerUrl: https://github.com/IanDarwin/pdfshow/releases/download/v1.1.1/PDFShow-1.1.1.msi
ManifestType: installer
ReleaseDate: 2024-11-19
PackageVersion: 1.1.1
PackageIdentifier: RejminetGroupInc.PDFShow

