AppsAndFeaturesEntries:
- DisplayVersion: 1.0.0
  UpgradeCode: '{58832A38-D27F-4F3A-8A9F-2028F95FAEE6}'
  ProductCode: '{7FA33D16-D79D-48EF-BCED-C85C29110BED}'
ProductCode: '{7FA33D16-D79D-48EF-BCED-C85C29110BED}'
Scope: machine
PackageIdentifier: ANTOrg-Inc.ASCIIEngine
ManifestType: installer
ReleaseDate: 2022-10-26
PackageVersion: "3.0"
ManifestVersion: 1.9.0
InstallerLocale: und
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/hdfsyu/ASCIIEngine/releases/download/v3.0/ASCIIEngine.msi
  InstallerSha256: 8D767358300A70FB4B6F07BCF31B8A698EEE9C060AB44C7AA73334174298A0C8
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%\.'
InstallerType: msi

