# Created with komac v2.10.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: bootandy.dust
PackageVersion: 1.1.1
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: dust-v1.1.1-x86_64-pc-windows-gnu/dust.exe
ReleaseDate: 2024-07-17
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/bootandy/dust/releases/download/v1.1.1/dust-v1.1.1-x86_64-pc-windows-gnu.zip
  InstallerSha256: EAD8EB39D931F3BB0ED23D8E58A27C583161D665FB98A5975D456059810602A9
ManifestType: installer
ManifestVersion: 1.9.0
