InstallerType: zip
NestedInstallerType: portable
ReleaseDate: 2025-02-14
ManifestVersion: 1.9.0
PackageIdentifier: Rclone.Rclone
ManifestType: installer
PackageVersion: 1.69.1
Installers:
- NestedInstallerFiles:
  - RelativeFilePath: rclone-v1.69.1-windows-386/rclone.exe
  Architecture: x86
  InstallerSha256: C7FDCF976C14FEE0B493508088AEB11A2B9B028B51444B69101B291AAD59E5FB
  InstallerUrl: https://github.com/rclone/rclone/releases/download/v1.69.1/rclone-v1.69.1-windows-386.zip
- NestedInstallerFiles:
  - RelativeFilePath: rclone-v1.69.1-windows-amd64/rclone.exe
  Architecture: x64
  InstallerSha256: 0803F06D721E5399E48794538294099B195D51CC84B27BDB67E131096AD93EE4
  InstallerUrl: https://github.com/rclone/rclone/releases/download/v1.69.1/rclone-v1.69.1-windows-amd64.zip
- NestedInstallerFiles:
  - RelativeFilePath: rclone-v1.69.1-windows-arm64/rclone.exe
  Architecture: arm64
  InstallerSha256: 0F8A786C1EAE54594BD067E05C1D22B3B346C5A8FB02392C446F63BAB52BE5AA
  InstallerUrl: https://github.com/rclone/rclone/releases/download/v1.69.1/rclone-v1.69.1-windows-arm64.zip

