ReleaseDate: 2025-02-17
PackageIdentifier: GoACME.lego
PackageVersion: 4.22.2
Installers:
- InstallerSha256: B9BF77F023EDF65540B796B4E430B8E8D0B80E719D3E5D21E6BD800760DBDD60
  Architecture: x86
  InstallerUrl: https://github.com/go-acme/lego/releases/download/v4.22.2/lego_v4.22.2_windows_386.zip
- InstallerSha256: B36D3E87617E928F80850B6EA67C66A5A02986DC7D425753200DA79A4CAAF55B
  Architecture: x64
  InstallerUrl: https://github.com/go-acme/lego/releases/download/v4.22.2/lego_v4.22.2_windows_amd64.zip
- InstallerSha256: 8793DF139485B195D652A5985FD486F43EC0A635F72A20C8180F64769DFD0C56
  Architecture: arm
  InstallerUrl: https://github.com/go-acme/lego/releases/download/v4.22.2/lego_v4.22.2_windows_armv7.zip
- InstallerSha256: EE56B0620134602D2E546B37686A77170F3A5186B18F8F6017F16C09F36F1BFF
  Architecture: arm64
  InstallerUrl: https://github.com/go-acme/lego/releases/download/v4.22.2/lego_v4.22.2_windows_arm64.zip
UpgradeBehavior: install
NestedInstallerFiles:
- RelativeFilePath: lego.exe
ManifestVersion: 1.9.0
InstallerLocale: en-US
NestedInstallerType: portable
ManifestType: installer
InstallerType: zip

