InstallerType: nullsoft
InstallerLocale: en-US
PackageVersion: 3.11.5
Scope: machine
InstallerSwitches:
  Silent: /S
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles(x86)%\gPodder'
ReleaseDate: 2024-12-20
AppsAndFeaturesEntries:
- ProductCode: gPodder
InstallModes:
- interactive
- silent
ManifestVersion: 1.9.0
UpgradeBehavior: uninstallPrevious
ManifestType: installer
ProductCode: gPodder
PackageIdentifier: gpodder.gpodder
Installers:
- InstallerSha256: 212A88B68469E9B83E920D950B260CE6A9EEA3FAE913E6A3BFF9833AB31BF6A1
  Architecture: x86
  InstallerUrl: https://github.com/gpodder/gpodder/releases/download/3.11.5/windows-gpodder-3.11.5-installer.exe

