name: Auto Merge Winget Update PRs

on:
  pull_request_target:
    types: [labeled]

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: >
      contains(github.event.label.name, 'winget-update')
    steps:
      - name: Merge Pull Request
        uses: peter-evans/merge-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: squash
          commit-title: "Auto-merge winget update: ${{ github.event.pull_request.title }}"
          commit-message: "Merged automatically by GitHub Actions."
