name: Auto Merge Winget Update PRs

on:
  pull_request:
    types: [ labeled ]

jobs:
  build:
    if: ${{ github.event.label.name == 'winger-update' }}
    runs-on: ubuntu-latest
    steps:
      - name: Merge Pull Request
        uses: peter-evans/merge-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: squash
          commit-title: "Auto-merge winget update: ${{ github.event.pull_request.title }}"
          commit-message: "Merged automatically by GitHub Actions."
