name: Commit Artifacts on Cancel

on:
  workflow_run:
    workflows: ["Update Winget Manifests"]
    types: [completed]

jobs:
  commit:
    if: ${{ github.event.workflow_run.conclusion == 'cancelled' }}
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: update-artifacts
          path: artifacts

      - name: Copy artifacts to repository root
        shell: pwsh
        run: |
          Copy-Item -Path "artifacts\last_checked.json" -Destination "$env:GITHUB_WORKSPACE\last_checked.json" -Force
          Copy-Item -Path "artifacts\komac" -Destination "$env:GITHUB_WORKSPACE\komac" -Recurse -Force

      - name: Commit and Push Changes
        shell: pwsh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add last_checked.json komac
          if (-not (git diff --cached --quiet)) {
              git commit -m "Update manifest state files on workflow cancel"
              git push
          }
          else {
              Write-Host "No changes to commit."
          }
