name: Update Winget Manifests

on:
  schedule:
    - cron: '0 0 * * *'         # Runs daily at midnight UTC
  workflow_dispatch:            # Allows manual triggering

jobs:
  update:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Copy required files from Scripts folder
        shell: pwsh
        run: |
          # Verify the Scripts folder exists
          if (!(Test-Path "$env:GITHUB_WORKSPACE\Scripts")) {
              Write-Error "Scripts folder not found in repository"
              exit 1
          }
          # Copy winget_ids.txt, last_checked.json, and the komac folder to the workspace root.
          Copy-Item -Path "$env:GITHUB_WORKSPACE\Scripts\winget_ids.txt" -Destination "$env:GITHUB_WORKSPACE\winget_ids.txt" -Force
          Copy-Item -Path "$env:GITHUB_WORKSPACE\Scripts\last_checked.json" -Destination "$env:GITHUB_WORKSPACE\last_checked.json" -Force
          Copy-Item -Path "$env:GITHUB_WORKSPACE\Scripts\.komac" -Destination "$env:GITHUB_WORKSPACE\.komac" -Recurse -Force
        working-directory: ${{ github.workspace }}

      - name: Install WinGet
        run: |
          Install-Module -Name Microsoft.WinGet.Client -Force -Scope CurrentUser -Repository PSGallery
          Repair-WinGetPackageManager -Latest -AllUsers -Verbose
          winget settings --enable LocalManifestFiles
          winget --info
          winget install wingetcreate --disable-interactivity --accept-source-agreements --accept-package-agreements
          wingetcreate info
          Copy-Item -Path wingetcreate_settings.json -Destination $env:LOCALAPPDATA\Packages\Microsoft.WindowsPackageManagerManifestCreator_8wekyb3d8bbwe\LocalState\settings.json -Force
          winget install komac --scope machine --disable-interactivity --accept-source-agreements --accept-package-agreements
          $env:Path = [System.Environment]::GetEnvironmentVariable("Path","Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path","User")
        working-directory: Automations

      - name: Setup PowerShell Modules
        shell: pwsh
        run: |
          # Install powershell-yaml if not available
          if (-not (Get-Module -ListAvailable -Name powershell-yaml)) {
              Install-Module -Name powershell-yaml -Scope CurrentUser -Force -AllowClobber
          }
          # Install a Winget module if needed (example: PSWinget)
          if (-not (Get-Module -ListAvailable -Name PSWinget)) {
              Install-Module -Name PSWinget -Scope CurrentUser -Force -AllowClobber
          }
          Write-Host "Required modules installed."

      - name: Run Update Script
        shell: pwsh
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
          KOMAC_PATH: 'C:\Program Files\Komac\bin\Komac.exe'
        run: |
          # Ensure the update script is executable and run it.
          # The script uses environment variables for sensitive info.
          .\Scripts\CheckAndUpdateFromWingetManifest.ps1
          
      - name: Commit and Push Changes
        if: always()
        shell: pwsh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add last_checked.json .komac
          if (-not (git diff --cached --quiet)) {
              git commit -m "Update manifest state files via GitHub Action"
              git push
          }
          else {
              Write-Host "No changes to commit."
          }
