Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.VCRedist.2015+.x64
ManifestType: installer
ElevationRequirement: elevatesSelf
InstallerLocale: en-US
Scope: machine
Installers:
- InstallerSha256: 0FF7EF5A18A04F13131A870FBC8F1CD0C0B249071CB76C737FFCE18E5A1112B7
  InstallerUrl: https://github.com/odamex/odamex/releases/download/10.6.0/odamex-win-10.6.0.exe
  Architecture: x86
InstallerType: inno
ManifestVersion: 1.9.0
PackageIdentifier: Odamex.Odamex
AppsAndFeaturesEntries:
- ProductCode: '{2E517BBB-916F-4AB6-80E0-D4A292513F7A}_is1'
  Publisher: Odamex Development Team
InstallerSwitches:
  Custom: /ALLUSERS
ProductCode: '{2E517BBB-916F-4AB6-80E0-D4A292513F7A}_is1'
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%\Odamex'
PackageVersion: 10.6.0
ReleaseDate: 2024-09-11

